"""quitar subtitle

Revision ID: 8597549914c8
Revises: 2cb3bab0896d
Create Date: 2026-04-20 11:19:29.744472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8597549914c8'
down_revision: Union[str, Sequence[str], None] = '2cb3bab0896d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'subtitle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('subtitle', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
