"""agregar columnas a user

Revision ID: 9054eb2c7c62
Revises: 8597549914c8
Create Date: 2026-04-20 22:43:01.885396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9054eb2c7c62'
down_revision: Union[str, Sequence[str], None] = '8597549914c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('top_category', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('top_books', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'top_books')
    op.drop_column('users', 'top_category')
    # ### end Alembic commands ###
